# Generated by Django 3.1.7 on 2021-03-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210311_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='rol',
            field=models.CharField(default='Rol', max_length=20),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='descripcion',
            field=models.TextField(default='Descripción'),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=30),
        ),
    ]
