# Generated by Django 3.1.7 on 2021-03-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210311_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='image',
            field=models.ImageField(null=True, upload_to='models/personaje/images'),
        ),
    ]
